import mongoose from 'mongoose';

const qrCodeSchema = new mongoose.Schema({
  location:   { type: String, required: true },
  department: { type: String, default: 'All' },
  type:       { type: String, enum: ['CHECKIN', 'CHECKOUT', 'MANUAL'], default: 'MANUAL' },
  token:      String,
  url:        String,
  qrDataUrl:  String,
  expiresAt:  Date,
  isActive:   { type: Boolean, default: true },
  isAuto:     { type: Boolean, default: false }, // auto-generated by scheduler
  createdBy:  { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  scanCount:  { type: Number, default: 0 },
}, { timestamps: true });

export default mongoose.model('QRCode', qrCodeSchema);
